### ISSUE TITLE
Add code analizer

### ISSUE THREAD

**Issue by IhorMruchko** [IhorMruchko/ScheduleLNU#4]
- [ ] Sonar
      https://www.nuget.org/packages/SonarAnalyzer.CSharp/
- [ ] StyleCop
       https://www.nuget.org/packages/StyleCop.Analyzers/
- [ ] Roslynator
       https://www.nuget.org/packages/Roslynator.Analyzers/

**Comment by PavloPol27** [comment]
1) Стаття про порівняння StyleCop і Sonar:  https://medium.com/@michaelparkerdev/linting-c-in-2019-stylecop-sonar-resharper-and-roslyn-73e88af57ebd. Якщо коротко, то StyleCop працює як швидкий аналізатор коду з можливістю автоматично виправляти помилки. Sonar, в порівнянні з StyleCop, більше розрахований на глибокий аналіз коду, тобто на складність написання, і не виправляє помилки автоматично. Можна їх використовувати одночасно в проекті. Також можна налаштовувати на що варто звертати увагу при виправленні, на що ні.

2) Roslynator по суті майже не відрізняється по функціоналу від StyleCop. Тут коротка стаття про цей аналайзер, як встановлювати, приклад, як він працює https://blog.klimczyk.pl/posts/2018/10/roslynator-code-analysis.

На мою думку, можна вибирати між Roslynator і StyleCop і цього буде цілком достатньо для нашого проекту.
