### ISSUE TITLE
Add unit-tests

### ISSUE THREAD

**Issue by IhorMruchko** [IhorMruchko/ScheduleLNU#7]
- [x] xUnit
- [x] NUnit

**Comment by Loathriel** [comment]
xUnit:
 + Простіший в використанні і розумінні
 + Код виглядає чистішим ніж при інших тестах
 + Легко можна розширити для своїх необхідностей
 +- Кожен тест це окрема структура (менша залежність, але трохи довший час на виконання)
 - Мала кількість документації
 - Трохи менший наперед визначений функціонал
 
NUnit:
 + Багато посібників по використанню
 + Можливість використовувати різний функціонал
 - Менш гнучкий поза базовим функціоналом
 
 https://www.quora.com/What-are-the-pros-and-cons-of-NUnit-and-XUnit
 https://www.slant.co/topics/543/~best-unit-testing-frameworks-for-net
 https://www.c-sharpcorner.com/UploadFile/Santhi.M/comparison-of-unit-testing-tools-in-net/
